### ISSUE TITLE
Make HugeNum instance of Generic?

### ISSUE THREAD

**Issue by chexxor** [purescript-contrib/purescript-precise#3]
I'd like to make HugeNum an instance of Generic, but I get an error message when I try `derive instance genericHugeNum :: Generic HugeNum` because HugeRec is a type synonym. Looks like this isn't possible right now because `derive generic` doesn't work with a type synonym like this. See: https://github.com/purescript/purescript/issues/1443

After that's fixed, we can make this an instance of Generic.

**Comment by garyb** [comment]
It is still possible to provide a generic instance, we'll just have to write it rather than deriving it. Alternatively we could duplicate the record in the newtype, since the two will still unify:

``` purescript
type HugeRec = { digits :: List Digit, decimal :: Int, sign :: Sign }
newtype HugeNum = HugeNum { digits :: List Digit, decimal :: Int, sign :: Sign }
```

And then deriving should be possible.
